### ISSUE TITLE
Security Chip

### ISSUE THREAD

**Issue by abhatikar** [Microsoft/devkit-sdk#823]
Hi,

Is there a sample showing how to use the security chip for the Az3166 board ?
A small sample code would be very helpful.
thanks in advance,

**Comment by ihere1** [comment]
API reference at https://microsoft.github.io/azure-iot-developer-kit/docs/apis/EEPROMInterface/

**Comment by ihere1** [comment]
The secure channel can not be disabled. It is a by design feature for secure. And the behavior before secure channel enabled and after secure channel enabled is the same. The only difference is data storage format on secure chip and the application code can not tell whether secure channel is enabled. Secure channel is to make sure host board(devkit) and secure chip can verify each other in industrial environment. 
You can enable secure channel any time. Do you need a sample code with only read and write ?

**Comment by abhatikar** [comment]
Thanks for your reply @ihere1.Sure if you could share some sample that would be helpful. I did not quite get the idea and benefit of having the secured chip.

**Comment by ihere1** [comment]
After secure channel enabled, the data between secure chip and board will be encrypted. Other board without specific key can not read data from secure chip. But it is hard to demo. For devkit, the secure chip is still a storage even after secure channel enabled. Encryption and decryption were completed in lower level library.
